USE ecommerce_analytics_db;
CREATE TABLE data_inventory_raw (
    id INT AUTO_INCREMENT PRIMARY KEY,
    InventoryDate DATETIME NOT NULL,
    SKU VARCHAR(50) NOT NULL,
    Product_Name VARCHAR(255),
    ProductTypeName VARCHAR(100),
    UPC BIGINT,
    Name VARCHAR(255),
    LocationNotes TEXT,
    Warehouse VARCHAR(100),
    Bin_Name VARCHAR(100),
    Physical INT DEFAULT 0,
    Reserved INT DEFAULT 0,
    Available INT DEFAULT 0,
    Last_Received DATE,
    Cost DECIMAL(10,2),
    CostType VARCHAR(50),
    Value DECIMAL(10,2),
    List_Price DECIMAL(10,2),
    Site_Price DECIMAL(10,2),
    INDEX idx_sku (SKU),
    INDEX idx_inventory_date (InventoryDate),
    INDEX idx_warehouse (Warehouse)
);